ExampleModelName:
    namespace: \Example\Name\Space
    method: getObject
    gc: '100'
ExampleModelNameTwo:
    namespace: ''
    method: getModel
    gc: '0'
ExampleModelNameThree:
    namespace: \Some\Other\Name\Space
    method: getMultiObject
    gc: '42'
