ExampleModelName:
    namespace: \Example\Name\Space
    function: getObject
    gc: '100'
ExampleModelNameTwo:
    namespace: ''
    function: getModel
    gc: '0'
ExampleModelNameThree:
    namespace: \Some\Other\Name\Space
    function: getMultiObject
    gc: '42'
